version: '3'

services:
  yona:
    build: .
    image: pokev25/yona:1.15.0
    restart: always
    environment:
      - BEFORE_SCRIPT=before.sh
      - JAVA_OPTS=-Xmx2048m -Xms1024m
    volumes:
      - ./data:/yona/data
    ports:
      - "9000:9000"
  yona-db:
    image: mariadb:10.3
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root1234
      - MARIADB_USER=yona
      - MARIADB_PASSWORD=pass1234
      - MARIADB_DATABASE=yona
    volumes:
      - ./yona-db:/var/lib/mysql